---
engines:
  fixme:
    enabled: true
  pmd:
    enabled: true
    channel: "beta"
ratings:
  paths:
  - "**.java"
exclude_paths: 
- spec/**/*
- "**/vendor/**/*"
- app/src/main/java/sonic/**
- app/src/main/java/com/github/**
