language: android
android:
  components:
    # The BuildTools version used by your project
    - tools
    - platform-tools
    - build-tools-25.0.2

    # The SDK version used to compile your project
    - android-25

    # Additional components
    - extra-android-m2repository
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
script:
  ./gradlew build check
