language: android
android:
  components:
    # The BuildTools version used by your project
    - build-tools-23.0.1
    - platform-tools

    # The SDK version used to compile your project
    - android-23

    # Additional components
    - extra-android-m2repository
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
script:
  ./gradlew build check