header-img: img/thumbs-up.jpg
baseurl: /aesopPlayer
plugins:
 - jekyll-sitemap
 - jekyll-redirect-from
defaults:
  -
    scope:
      path: "" # all pages
      type: "pages"
    values:
      meta_og:
        path: "/"
        admins: "xxxxxxxxxxxxxxx"
        type: "website"
        title: "An audiobook player particularly for seniors"
        description: "A free app that converts an Android tablet into an audiobook player, with partucular focus on the elderly and visually impaired."
        image:
          path: "/img/thumbs-up.jpg"
          width: 1200
          height: 630
        video_url: "https://youtu.be/yjj3P2VE6jk"
        video_url_secure: "https://youtu.be/yjj3P2VE6jk"
