header-img: img/default-header.jpg
baseurl: /homerplayer
gems:
 - jekyll-sitemap
defaults:
  -
    scope:
      path: "" # all pages
      type: "pages"
    values:
      meta_og:
        path: "/"
        admins: "100006228436823"
        type: "website"
        title: "An audiobook player for seniors"
        description: "A free app that converts an Android tablet into an audiobook player designed for the elderly and visually impaired."
        image:
          path: "/img/default-share.jpg"
          width: 1200
          height: 628
        video_url: "http://www.youtube.com/v/RfLkoLtxzng"
        video_url_secure: "https://www.youtube.com/v/RfLkoLtxzng"
